- name: install tomcat
  hosts: tomcat
  become: yes

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Ensure Docker  package is present
    apt:
      name: docker.io
      state: present

  - name: Ensure Docker-compose  package is present
    apt:
      name: docker-compose
      state: present
  
  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: yes

  - name: Start Docker service
    docker_container:
      name: dirtomcat
      image: micheldir/cert
      ports:
        - "8080:8080"

