- name: install tomcat
  hosts: tomcat
  become: yes

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Ensure Tomcat  package is present
    apt:
      name: tomcat9
      state: present

  - name: Enssure Project is WAR file is present
    shell: "gsutil cp gs://micheldirmaven/java-tomcat-maven-example.war /var/lib/tomcat9/webapps/java-tomcat-maven-example.war"
