---
- name: build and push docker
  hosts: maven
  become: yes

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Ensure Docker  package is present
    apt:
      name: docker.io
      state: present


  - name: Ensure Docker-compose  package is present
    apt:
      name: docker-compose
      state: present


  - name: copy Dockerfile
    copy:
      src: ./dockerfile
      dest: /tmp/dockerfile

  - name: Log into DockerHub
    docker_login:
      username: micheldir
      password: "{{ pass }}"

  - name: build container image
    docker_image:
      name: micheldir/cert
      build:
        path: /tmp
      source: build
      state: present
      push: yes
